name: Build and Push to Amazon ECR

on:
  push:
    branches: [main]  # Automatically runs on push to main
  workflow_dispatch:
    inputs:
      claim_file_key:
        description: 'S3 object key for the claim file (e.g., raw/claim-documents/claim_123.pdf)'
        required: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CLAIM_KEY: ${{ github.event.inputs.claim_file_key != '' && github.event.inputs.claim_file_key || 'raw/claim-documents/sample-claim-document.pdf' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t aicp-claim-processing .
          docker tag aicp-claim-processing:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/aicp-claim-processing:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/aicp-claim-processing:latest

      - name: Register ECS Task Definition and Capture ARN
        id: register_task
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://ecs-task-definition.json \
            --query 'taskDefinition.taskDefinitionArn' --output text)
          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV
          echo "Registered task definition: $TASK_DEF_ARN"

      - name: Run ECS Task with Dynamic S3 Object Key
        run: |
          bucket="aicp-claims-data"
          key="${{ env.CLAIM_KEY }}"

          aws ecs run-task \
            --cluster aicp-ecs-cluster \
            --launch-type FARGATE \
            --task-definition ${{ env.TASK_DEF_ARN }} \
            --network-configuration "awsvpcConfiguration={subnets=[subnet-02c673bb70ede8519],securityGroups=[sg-0446ae2a3834b378e],assignPublicIp=ENABLED}" \
            --overrides "$(jq -n \
              --arg bucket "$bucket" \
              --arg key "$key" \
              '{ containerOverrides: [ { name: "aicp-claim-processing-container", environment: [ { name: "S3_BUCKET", value: $bucket }, { name: "S3_OBJECT_KEY", value: $key } ] } ] }')"

      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "AICP ECS CI/CD Pipeline - ${{ job.status }}"
          to: mm.cloudenginner@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            ✅ ECS Claim Processing Complete

            📁 S3 Object Key: ${{ env.CLAIM_KEY }}
            🟢 Status: ${{ job.status }}
            🔗 GitHub: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
